Resources:
  User1:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "ashisharyalabatajsjsdjsdjsdjsdjsdjban"
  User2:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "iamshisharyalabatabanyojsdjdsjsdjdjsniiiiid"
